#!/bin/bash
#SBATCH --job-name=fastqc_job
#SBATCH --output=fastqc_out.txt
#SBATCH --time=01:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G

module load fastqc
fastqc SRR18395025.fastq -o ./results/
